"""Add verified clinical-stage biotech companies via API.

Only includes companies known to have active clinical pipelines.
Skips gracefully if a ticker already exists in the system.
"""

import httpx, time, sys

BASE = "https://pharma-edge.onrender.com"

# Clean list — all confirmed clinical-stage biotech/pharma companies
TICKERS = [
    # ── Large-cap additions ──
    ("ABBV", "AbbVie Inc."),
    ("BMY", "Bristol-Myers Squibb"),
    ("JNJ", "Johnson & Johnson"),
    ("LLY", "Eli Lilly and Company"),
    ("MRK", "Merck & Co. Inc."),
    ("NVS", "Novartis AG"),
    ("NVO", "Novo Nordisk A/S"),
    ("PFE", "Pfizer Inc."),
    ("SNY", "Sanofi S.A."),
    ("TAK", "Takeda Pharmaceutical Company"),

    # ── Mid/Small-cap clinical-stage ──
    ("ACAD", "ACADIA Pharmaceuticals"),
    ("ACIU", "AC Immune SA"),
    ("ACLX", "Arcellx Inc."),
    ("ADMA", "ADMA Biologics"),
    ("ADPT", "Adaptive Biotechnologies"),
    ("ADVM", "Adverum Biotechnologies"),
    ("AKRO", "Akero Therapeutics"),
    ("ALEC", "Alector Inc."),
    ("ALKS", "Alkermes PLC"),
    ("ALLO", "Allogene Therapeutics"),
    ("ALNY", "Alnylam Pharmaceuticals"),
    ("ALT", "Altimmune Inc."),
    ("AMAM", "Ambrx Biopharma"),
    ("AMLX", "Amylyx Pharmaceuticals"),
    ("ANAB", "AnaptysBio Inc."),
    ("ANNX", "Annexon Inc."),
    ("APLS", "Apellis Pharmaceuticals"),
    ("APLT", "Applied Therapeutics"),
    ("ARDX", "Ardelyx Inc."),
    ("ARQT", "Arcutis Biotherapeutics"),
    ("ARVN", "Arvinas Inc."),
    ("ARWR", "Arrowhead Pharmaceuticals"),
    ("ATHA", "Athira Pharma"),
    ("ATRA", "Atara Biotherapeutics"),
    ("ATYR", "aTyr Pharma Inc."),
    ("AUPH", "Aurinia Pharmaceuticals"),
    ("AVIR", "Atea Pharmaceuticals"),
    ("AVRO", "AVROBIO Inc."),
    ("AXSM", "Axsome Therapeutics"),
    ("BBIO", "BridgeBio Pharma"),
    ("BCAB", "BioAtla Inc."),
    ("BCRX", "BioCryst Pharmaceuticals"),
    ("BCYC", "Bicycle Therapeutics"),
    ("BEAM", "Beam Therapeutics"),
    ("BHVN", "Biohaven Pharmaceutical"),
    ("BIIB", "Biogen Inc."),
    ("BLUE", "bluebird bio Inc."),
    ("BMRN", "BioMarin Pharmaceutical"),
    ("BPMC", "Blueprint Medicines"),
    ("BTAI", "BioXcel Therapeutics"),
    ("CALT", "Calliditas Therapeutics"),
    ("CAPR", "Capricor Therapeutics"),
    ("CARA", "Cara Therapeutics"),
    ("CERE", "Cerevel Therapeutics"),
    ("CGEM", "Cullinan Therapeutics"),
    ("CGEN", "Compugen Ltd."),
    ("CGON", "CG Oncology Inc."),
    ("CHRS", "Coherus BioSciences"),
    ("CLDX", "Celldex Therapeutics"),
    ("CMPX", "Compass Therapeutics"),
    ("CNTA", "Centessa Pharmaceuticals"),
    ("CORT", "Corcept Therapeutics"),
    ("CPRX", "Catalyst Pharmaceuticals"),
    ("CRBU", "Caribou Biosciences"),
    ("CRIS", "Curis Inc."),
    ("CRSP", "CRISPR Therapeutics"),
    ("CRVS", "Corvus Pharmaceuticals"),
    ("CTMX", "CytomX Therapeutics"),
    ("CVAC", "CureVac N.V."),
    ("CYBN", "Cybin Inc."),
    ("CYTK", "Cytokinetics Inc."),
    ("DAWN", "Day One Biopharmaceuticals"),
    ("DCPH", "Deciphera Pharmaceuticals"),
    ("DNLI", "Denali Therapeutics"),
    ("DNTH", "Dianthus Therapeutics"),
    ("DVAX", "Dynavax Technologies"),
    ("DYN", "Dyne Therapeutics"),
    ("EDIT", "Editas Medicine"),
    ("ELVN", "Enliven Therapeutics"),
    ("ENTA", "Enanta Pharmaceuticals"),
    ("ERAS", "Erasca Inc."),
    ("ETNB", "89bio Inc."),
    ("EWTX", "Edgewise Therapeutics"),
    ("EXEL", "Exelixis Inc."),
    ("EYPT", "EyePoint Pharmaceuticals"),
    ("FATE", "Fate Therapeutics"),
    ("FDMT", "4D Molecular Therapeutics"),
    ("FGEN", "FibroGen Inc."),
    ("FHTX", "Foghorn Therapeutics"),
    ("FOLD", "Amicus Therapeutics"),
    ("FULC", "Fulcrum Therapeutics"),
    ("GERN", "Geron Corporation"),
    ("GILD", "Gilead Sciences"),
    ("GLPG", "Galapagos NV"),
    ("GLYC", "GlycoMimetics Inc."),
    ("GMAB", "Genmab A/S"),
    ("GPCR", "Structure Therapeutics"),
    ("GRCL", "Gracell Biotechnologies"),
    ("HALO", "Halozyme Therapeutics"),
    ("HCM", "HUTCHMED (China) Ltd"),
    ("HRMY", "Harmony Biosciences"),
    ("HRTX", "Heron Therapeutics"),
    ("IBRX", "ImmunityBio Inc."),
    ("IDYA", "IDEAYA Biosciences"),
    ("IGMS", "IGM Biosciences"),
    ("IKNA", "Ikena Oncology"),
    ("IMAB", "I-Mab Biopharma"),
    ("IMCR", "Immunocore Holdings"),
    ("IMGN", "ImmunoGen Inc."),
    ("IMNM", "Immunome Inc."),
    ("IMTX", "Immatics N.V."),
    ("INCY", "Incyte Corporation"),
    ("INO", "Inovio Pharmaceuticals"),
    ("INSM", "Insmed Inc."),
    ("IONS", "Ionis Pharmaceuticals"),
    ("IOVA", "Iovance Biotherapeutics"),
    ("IRON", "Disc Medicine Inc."),
    ("ITOS", "iTeos Therapeutics"),
    ("JANX", "Janux Therapeutics"),
    ("JAZZ", "Jazz Pharmaceuticals"),
    ("KALA", "Kala Pharmaceuticals"),
    ("KALV", "KalVista Pharmaceuticals"),
    ("KNSA", "Kiniksa Pharmaceuticals"),
    ("KOD", "Kodiak Sciences"),
    ("KPTI", "Karyopharm Therapeutics"),
    ("KRYS", "Krystal Biotech"),
    ("KURA", "Kura Oncology"),
    ("KYMR", "Kymera Therapeutics"),
    ("KYVA", "Kyverna Therapeutics"),
    ("LBPH", "Longboard Pharmaceuticals"),
    ("LCTX", "Lineage Cell Therapeutics"),
    ("LGND", "Ligand Pharmaceuticals"),
    ("LPCN", "Lipocine Inc."),
    ("LXRX", "Lexicon Pharmaceuticals"),
    ("LYEL", "Lyell Immunopharma"),
    ("MCRB", "Seres Therapeutics"),
    ("MDGL", "Madrigal Pharmaceuticals"),
    ("MESO", "Mesoblast Limited"),
    ("MGTX", "MeiraGTx Holdings"),
    ("MIRM", "Mirum Pharmaceuticals"),
    ("MLYS", "Mineralys Therapeutics"),
    ("MORF", "Morphic Holding"),
    ("MRKR", "Marker Therapeutics"),
    ("MRNS", "Marinus Pharmaceuticals"),
    ("MRSN", "Mersana Therapeutics"),
    ("MRTX", "Mirati Therapeutics"),
    ("MRNA", "Moderna Inc."),
    ("MURA", "Mural Oncology"),
    ("NAMS", "NewAmsterdam Pharma"),
    ("NBIX", "Neurocrine Biosciences"),
    ("NKTR", "Nektar Therapeutics"),
    ("NMRA", "Neumora Therapeutics"),
    ("NRXP", "NRx Pharmaceuticals"),
    ("NTLA", "Intellia Therapeutics"),
    ("NVAX", "Novavax Inc."),
    ("NVTA", "Invitae Corporation"),
    ("OCEA", "Ocean Biomedical"),
    ("OCGN", "Ocugen Inc."),
    ("OCUL", "Ocular Therapeutix"),
    ("OLMA", "Olema Pharmaceuticals"),
    ("OMER", "Omeros Corporation"),
    ("ONCO", "Onconova Therapeutics"),
    ("ONCT", "Oncternal Therapeutics"),
    ("ONCY", "Oncolytics Biotech"),
    ("ONVO", "Organovo Holdings"),
    ("OPK", "OPKO Health Inc."),
    ("OPTN", "OptiNose Inc."),
    ("ORIC", "ORIC Pharmaceuticals"),
    ("ORMP", "Oramed Pharmaceuticals"),
    ("PASG", "Passage Bio Inc."),
    ("PBYI", "Puma Biotechnology"),
    ("PCRX", "Pacira BioSciences"),
    ("PDSB", "PDS Biotechnology"),
    ("PEPG", "PepGen Inc."),
    ("PGEN", "Precigen Inc."),
    ("PHAR", "Pharming Group"),
    ("PHAT", "Phathom Pharmaceuticals"),
    ("PHVS", "Pharvaris N.V."),
    ("PLRX", "Pliant Therapeutics"),
    ("PLX", "Protalix BioTherapeutics"),
    ("PMVP", "PMV Pharmaceuticals"),
    ("PRLD", "Prelude Therapeutics"),
    ("PRME", "Prime Medicine"),
    ("PROK", "ProKidney Corporation"),
    ("PRQR", "ProQR Therapeutics"),
    ("PRTA", "Prothena Corporation"),
    ("PTCT", "PTC Therapeutics"),
    ("PTGX", "Protagonist Therapeutics"),
    ("PYXS", "Pyxis Oncology"),
    ("QTTB", "Q32 Bio Inc."),
    ("QURE", "uniQure N.V."),
    ("RAPT", "RAPT Therapeutics"),
    ("RARE", "Ultragenyx Pharmaceutical"),
    ("RCKT", "Rocket Pharmaceuticals"),
    ("RCUS", "Arcus Biosciences"),
    ("REGN", "Regeneron Pharmaceuticals"),
    ("REPL", "Replimune Group"),
    ("RGNX", "REGENXBIO Inc."),
    ("RGLS", "Regulus Therapeutics"),
    ("RLAY", "Relay Therapeutics"),
    ("RLMD", "Relmada Therapeutics"),
    ("RLYB", "Rallybio Corporation"),
    ("RNA", "Avidity Biosciences"),
    ("RNAC", "Cartesian Therapeutics"),
    ("ROIV", "Roivant Sciences"),
    ("RPTX", "Repare Therapeutics"),
    ("RVMD", "Revolution Medicines"),
    ("RVNC", "Revance Therapeutics"),
    ("RXRX", "Recursion Pharmaceuticals"),
    ("RYTM", "Rhythm Pharmaceuticals"),
    ("RZLT", "Rezolute Inc."),
    ("SABS", "SAB Biotherapeutics"),
    ("SAGE", "Sage Therapeutics"),
    ("SANA", "Sana Biotechnology"),
    ("SAVA", "Cassava Sciences"),
    ("SCPH", "scPharmaceuticals"),
    ("SGEN", "Seagen Inc."),
    ("SGMO", "Sangamo Therapeutics"),
    ("SIGA", "SIGA Technologies"),
    ("SLDB", "Solid Biosciences"),
    ("SLGL", "Sol-Gel Technologies"),
    ("SLN", "Silence Therapeutics"),
    ("SLNO", "Soleno Therapeutics"),
    ("SLRN", "ACELYRIN Inc."),
    ("SMMT", "Summit Therapeutics"),
    ("SNGX", "Soligenix Inc."),
    ("SPRB", "Spruce Biosciences"),
    ("SPRY", "ARS Pharmaceuticals"),
    ("SRPT", "Sarepta Therapeutics"),
    ("SRRK", "Scholar Rock Holding"),
    ("STOK", "Stoke Therapeutics"),
    ("STRO", "Sutro Biopharma"),
    ("SUPN", "Supernus Pharmaceuticals"),
    ("SVRA", "Savara Inc."),
    ("SWTX", "SpringWorks Therapeutics"),
    ("SYBX", "Synlogic Inc."),
    ("SYRE", "Spyre Therapeutics"),
    ("TARA", "Protara Therapeutics"),
    ("TARS", "Tarsus Pharmaceuticals"),
    ("TBPH", "Theravance Biopharma"),
    ("TCRX", "TScan Therapeutics"),
    ("TERN", "Terns Pharmaceuticals"),
    ("TGTX", "TG Therapeutics"),
    ("TIL", "Instil Bio Inc."),
    ("TMDI", "Titan Medical Inc."),
    ("TNGX", "Tango Therapeutics"),
    ("TNYA", "Tenaya Therapeutics"),
    ("TPST", "Tempest Therapeutics"),
    ("TRDA", "Entrada Therapeutics"),
    ("TRML", "Tourmaline Bio Inc."),
    ("TRVI", "Trevi Therapeutics"),
    ("TSHA", "Taysha Gene Therapies"),
    ("TVTX", "Travere Therapeutics"),
    ("TYRA", "Tyra Biosciences"),
    ("UBX", "Unity Biotechnology"),
    ("UNCY", "Unicycive Therapeutics"),
    ("URGN", "UroGen Pharma"),
    ("UTHR", "United Therapeutics"),
    ("VCEL", "Vericel Corporation"),
    ("VCNX", "Vaccinex Inc."),
    ("VCYT", "Veracyte Inc."),
    ("VERA", "Vera Therapeutics"),
    ("VERU", "Veru Inc."),
    ("VERV", "Verve Therapeutics"),
    ("VIGL", "Vigil Neuroscience"),
    ("VIR", "Vir Biotechnology"),
    ("VIRX", "Viracta Therapeutics"),
    ("VKTX", "Viking Therapeutics"),
    ("VNDA", "Vanda Pharmaceuticals"),
    ("VOR", "Vor Biopharma"),
    ("VRCA", "Verrica Pharmaceuticals"),
    ("VRDN", "Viridian Therapeutics"),
    ("VRNA", "Verona Pharma"),
    ("VSTM", "Verastem Oncology"),
    ("VTGN", "Vistagen Therapeutics"),
    ("VTRS", "Viatris Inc."),
    ("VTYX", "Ventyx Biosciences"),
    ("VXRT", "Vaxart Inc."),
    ("WVE", "Wave Life Sciences"),
    ("XBIT", "XBiotech Inc."),
    ("XENE", "Xenon Pharmaceuticals"),
    ("XERS", "Xeris Biopharma Holdings"),
    ("XFOR", "X4 Pharmaceuticals"),
    ("XNCR", "Xencor Inc."),
    ("XOMA", "XOMA Corporation"),
    ("YMAB", "Y-mAbs Therapeutics"),
    ("ZLAB", "Zai Lab Limited"),
    ("ZNTL", "Zentalis Pharmaceuticals"),
    ("ZURA", "Zura Bio Limited"),
    ("ZVRA", "Zevra Therapeutics"),
    ("ZYME", "Zymeworks Inc."),
]

def main():
    added = 0
    skipped = 0
    errors = 0
    total = len(TICKERS)

    print(f"Adding up to {total} clinical-stage biotech companies...\n")

    for i, (sym, name) in enumerate(TICKERS, 1):
        try:
            r = httpx.post(
                f"{BASE}/api/tickers",
                json={"ticker": sym, "company_name": name, "sector": "Biotech"},
                timeout=65,
            )
            if r.status_code == 201:
                added += 1
                print(f"  [{i:3d}/{total}] + {sym:6s} {name}")
            elif r.status_code == 409:
                skipped += 1
            else:
                errors += 1
                print(f"  [{i:3d}/{total}] x {sym}: HTTP {r.status_code}")
        except Exception as e:
            errors += 1
            print(f"  [{i:3d}/{total}] ! {sym}: {type(e).__name__}")

        time.sleep(0.3)

    print(f"\n=== Summary ===")
    print(f"Added:   {added}")
    print(f"Already: {skipped}")
    print(f"Errors:  {errors}")
    print(f"Total tracked (incl. 31 seed): {added + 31 + skipped}")

if __name__ == "__main__":
    main()
